[package]
name = "mtg_webserver"
version = "0.1.0"
authors = ["Elchanan Haas <haas2376@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.5.0"
rand = {version="0.8.4",features = ["getrandom"]}
rand_xoshiro = "0.6.0"
hecs = "0.7.1"
anyhow = "1.0.51"
strum_macros = "0.23.1"