[package]
name = "mtg_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mtg_log_macro = { path = "../mtg_log_macro" }
common = { path = "../common" }
